version: 2

updates:
  - package-ecosystem: gradle
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Samara
    open-pull-requests-limit: 5
    groups:
      gradle-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
      day: tuesday
      time: "06:00"
      timezone: Europe/Samara
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci(deps)"
